### ISSUE TITLE
Interday rates

### ISSUE THREAD

**Issue by dannytsang** [christopherpthomas/MMM-OctoMon#5]
Is it possible to have an option to display the rates at certain intervals? E.g 30 minutes to hourly?

**Comment by christopherpthomas** [comment]
Hi Danny! Sorry for my slow reply. I'm not on Octopus's Agile tariff, but it's something that I would like to look at if i find the time. This is obviously a second set of information, and would require a second table, so what sort of layout would you be looking at? I'm wondering if everything would work if it was all crammed into one module, or if a second separate magic mirror module would be in order (which would allow more options with positioning and sizing etc).

**Comment by dannytsang** [comment]
Hi Christopher,

To be honest I have moved away from agile now as well. I was looking for a 30 minute rate for the day. Like the example shown here: https://github.com/markgdev/home-assistant_OctopusAgile/tree/master/custom_cards
